// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDon6QQawyUcANe2lJXkOmVLuuVKJuZii4',
    appId: '1:904700502952:web:9b8f0f02e573d676c7b39d',
    messagingSenderId: '904700502952',
    projectId: 'chat-1360a',
    authDomain: 'chat-1360a.firebaseapp.com',
    databaseURL: 'https://chat-1360a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-1360a.firebasestorage.app',
    measurementId: 'G-YX1F796HG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-LAh4UFOVvBX0blN1kFaAiXMUNvGFtZ8',
    appId: '1:904700502952:android:4b8411b2131d1176c7b39d',
    messagingSenderId: '904700502952',
    projectId: 'chat-1360a',
    databaseURL: 'https://chat-1360a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-1360a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DaSP9IiW3Ymqfsb3gpZHD3jzOf6r-PA',
    appId: '1:904700502952:ios:ddde7406b41560a4c7b39d',
    messagingSenderId: '904700502952',
    projectId: 'chat-1360a',
    databaseURL: 'https://chat-1360a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-1360a.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DaSP9IiW3Ymqfsb3gpZHD3jzOf6r-PA',
    appId: '1:904700502952:ios:ddde7406b41560a4c7b39d',
    messagingSenderId: '904700502952',
    projectId: 'chat-1360a',
    databaseURL: 'https://chat-1360a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-1360a.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDon6QQawyUcANe2lJXkOmVLuuVKJuZii4',
    appId: '1:904700502952:web:07ce2f479879bb8bc7b39d',
    messagingSenderId: '904700502952',
    projectId: 'chat-1360a',
    authDomain: 'chat-1360a.firebaseapp.com',
    databaseURL: 'https://chat-1360a-default-rtdb.firebaseio.com',
    storageBucket: 'chat-1360a.firebasestorage.app',
    measurementId: 'G-FCK52BDEHD',
  );
}
